/**
 * Conjecture DSL — types for mathematical conjectures about financial time series.
 * Used by the Conjecturer, Critic, Selector, Formalizer, and downstream agents.
 */

export type ConjectureDomain =
  | 'distributional'         // Properties of return distributions (moments, tails)
  | 'topological'            // Persistent homology, Betti numbers
  | 'dynamical'              // Lyapunov exponents, attractors, recurrence
  | 'information_theoretic'  // Entropy, mutual information, transfer entropy
  | 'microstructural'        // Order flow, arrival times, queue dynamics
  | 'cross_scale'            // Relationships between timeframes
  | 'game_theoretic';        // Equilibria, mean-field, mechanism design

export type ConjectureType =
  | 'existential'   // exists a structure with property P
  | 'universal'     // for all instruments/periods, property P holds
  | 'conditional'   // if condition C, then property P
  | 'comparative'   // structure A > structure B on metric M
  | 'equivalence'   // structure A ~ structure B under transformation T
  | 'bound';        // property P is bounded by f(parameters)

export type ConjectureStatus =
  | 'proposed'      // generated by Conjecturer
  | 'screened'      // passed Critic + Selector
  | 'formalized'    // translated to Lean 4
  | 'proving'       // proof attempt in progress
  | 'proved'        // Lean compiler verified the proof
  | 'falsified'     // counterexample found
  | 'inconclusive'  // neither proved nor disproved (timeout/resource limit)
  | 'generalized'   // extended by the Abstractor
  | 'superseded';   // replaced by a generalization

export interface FitnessDimensions {
  /** How novel compared to existing pool entries. [0,1] */
  novelty: number;
  /** Coherence with data profile and existing theory. [0,1] */
  plausibility: number;
  /** Expressibility in Lean 4 (based on available Mathlib). [0,1] */
  formalizability: number;
  /** Relevance to understanding market structure. [0,1] */
  relevance: number;
}

export interface FitnessScore extends FitnessDimensions {
  /** Weighted composite of the dimensions. [0,1] */
  composite: number;
}

export const DEFAULT_FITNESS_WEIGHTS: Record<keyof FitnessDimensions, number> = {
  novelty: 0.25,
  plausibility: 0.30,
  formalizability: 0.20,
  relevance: 0.25,
};

export interface Variable {
  name: string;
  source: string;             // e.g. "EURUSD" or "returns(EURUSD, M5)"
  type: 'series' | 'scalar' | 'distribution';
  domain?: string;            // mathematical domain (R, R+, [0,1], ...)
}

export interface Conjecture {
  id: string;                 // C-001, C-002, ...
  generation: number;         // Discovery round
  parentIds: string[];        // Lineage (for mutation/crossover)

  // Content
  title: string;              // Short human-readable label
  natural_language: string;   // Complete statement in natural language
  formal_sketch: string;      // Pseudo-Lean or formal outline
  domain: ConjectureDomain;
  type: ConjectureType;

  // Variables involved
  variables: Variable[];

  // Scoring
  fitness: FitnessScore;
  status: ConjectureStatus;

  // Evidence tracking
  evidence: {
    supporting_data?: string;        // Reference to data profile findings
    critic_objections?: string[];    // Raised by the Critic
    counterexamples?: string[];      // Found by Counterexample Search
    lean_statement?: string;         // Path to .lean file with the statement
    proof_attempts?: number;         // Prover self-correction rounds
    generalization_scope?: string;   // Filled by Abstractor if proved
  };

  // Metadata
  created_at: string;              // ISO-8601
  last_modified: string;
}

export interface ConjectureBatch {
  round: number;
  generated_at: string;
  conjectures: Conjecture[];
}

export interface CriticReview {
  conjecture_id: string;
  objections: Array<{
    category: 'logical_error' | 'implicit_assumption' | 'unfalsifiable' | 'trivial' | 'confounding' | 'parsimony';
    description: string;
    severity: 'low' | 'medium' | 'high' | 'fatal';
  }>;
  robustness_rating: number;      // [0,1] — higher = more robust
  recommendation: 'keep' | 'revise' | 'reject';
}

export interface SelectorDecision {
  conjecture_id: string;
  fitness: FitnessScore;
  verdict: 'selected' | 'rejected';
  reason: string;
}
